# Generated by Django 4.2.6 on 2023-11-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectWeb', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(choices=[('NAIROBI', 'KIAMBU'), ('MURANGA', 'NYERI'), ('MERU', 'EMBU'), ('MOMBASA', 'MALINDI'), ('LAMU', 'KILIFI'), ('NAKURU', 'ELDORET'), ('KISUMU', 'KAKAMEGA'), ('NYAMIRA', 'KSII')], max_length=100),
        ),
    ]
