# Generated by Django 4.2.6 on 2023-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectWeb', '0005_alter_customer_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(choices=[('NAI', 'NAIROBI'), ('KIA', 'KIAMBU'), ('NYTOWN', 'NYERI'), ('MRU', 'MERU'), ('MBA', 'MOMBASA'), ('MOMBASA', 'MALINDI'), ('NKU', 'NAKURU'), ('KSM', 'KISUMU'), ('ELD', 'UANSINGISHU')], max_length=100),
        ),
    ]
