# Generated by Django 4.2.6 on 2023-11-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectWeb', '0006_alter_customer_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='constituency',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(choices=[('NAIROBI', 'NAIROBI'), ('KIAMBU', 'KIAMBU'), ('NYERI', 'NYERI'), ('MERU', 'MERU'), ('MOMBASA', 'MOMBASA'), ('MALINDI', 'MALINDI'), ('NAKURU', 'NAKURU'), ('KISUMU', 'KISUMU'), ('UANSINGISHU', 'UANSINGISHU')], max_length=100),
        ),
    ]
